PackageIdentifier: TTSConsulting.WSBSD
Publisher: TTSConsulting
PackageName: WSBSD
Description: A Windows Subsystem That allows Windows To Run BSD Distros' Terminals and Commands.
Locale: en-US
License: MIT
